increment 14
rainset/shortener pull request #15
Opened 2022-10-04 10:20 UTC by rainset

- add batch delete
- add check delete urk in handler

2022-10-05 06:38 UTC, rekby commented on internal/app/handlers.go
> +	if resultURL.Original == "" || err != nil {
Тут будут разные результаты в зависимости от того запрашивается ли url который не существовал изначально или удаленный.

2022-10-05 06:48 UTC, rekby commented on internal/app/handlers.go
> +		_ = a.s.DeleteBatchURL(cookieID, v)
Тут происходит батчевание запросов удаления на порции, но нет фоновой работы.

В задании указано что нужно отправлять задачи на удаление и тут же возвращать ответ, а батчеванием заниматься уже в другой горутине.

Этот момент важен чтобы потренировать передачу данных между горутинами и организовать их совместную работу.

2022-10-06 23:50 UTC, rainset commented on internal/app/handlers.go
> +		_ = a.s.DeleteBatchURL(cookieID, v)
не понял какой сервис нужно релизовать в фоне, завернул удаление в горутины

2022-10-08 13:00 UTC, rekby commented on internal/app/handlers.go
> +		_ = a.s.DeleteBatchURL(cookieID, v)
Из обработчика DeleteBatchURLHandler нужно отправлять в другую горутину url'ы для удаления.
В горутине удаления - url-ы накапливаются и фактическое удаление происходит пачками - по N штук или раз в Y минут/секунд или то и другое.

Цель - потренировать передачу задач между горутинами и объединять несколько мелких запросов в один большой.

Запуск новой горутины это немного другой сценарий и на нём не получится отработать передачу данных между уже работающими горутинами, т.е. теряется ценный опыт.

2022-10-11 05:46 UTC, rekby requested changes

2022-10-11 05:46 UTC, rekby commented on internal/queue/queue.go
> +type DeleteURLWorker struct {
Зачем тут нужно выделять отдельного воркера, а потом делать пул этих воркеров?
Кажется что они всё равно не смогут работать параллельно из-за захвата mutex-а.

и функционал удаления дублируется в queue и в worker. Если с удалением возникнут проблемы - непонятно где искать причину.

2022-10-11 05:46 UTC, rekby commented on internal/queue/queue.go
> +		err = q.s.DeleteBatchURL(q.urls)
Стоит избегать блокировок при походах во внешние системы: https://practicum-students.slack.com/archives/C03U68G13B3/p1665466589715169

2022-10-11 06:55 UTC, rainset commented on internal/queue/queue.go
> +type DeleteURLWorker struct {
queue.PeriodicURLDelete() - горутина которая удаляет по таймингу
а сами воркеры работают с каналом и удаляют пачками

я пока не додумался как сделать периодическое удаление через канал и воркеры

2022-10-11 09:34 UTC, merged